### ISSUE TITLE
utils::{TopicPartitionOffset, PartitionOffset} have Result fields

### ISSUE THREAD

**Issue by dead10ck** [spicavigo/kafka-rust#128]
Currently, the `utils::{TopicPartitionOffset, PartitionOffset}` structs' offset fields are `Result`s. In my opinion, it's kind of strange to have a struct with a `Result` in the middle of it for anything but maybe custom `Error` types. It can make error handling on the user-side really inconvenient.

Additionally, it's not entirely clear to me why `TopicPartitionOffset` is needed at all—it seems that it exists only to flatten responses, which leads to [lots of inefficient cloning](https://github.com/spicavigo/kafka-rust/blob/master/src/client/mod.rs#L1340) of data that it already had. I think in an instance like the linked one, it would be more appropriate to return a map which maps topics to `PartitionOffset`s; that way, only a move of one string is necessary, rather than a clone for every single offset response.

What do you think? I tried to start by changing the `Result`s to just their underlying type, but I can see it's a non-trivial refactor, so I thought I'd get your input first.

**Comment by xitep** [comment]
Many thanks for the investigation!

* I agree that the existence of `TopicPartitionOffset` is sub-optimal. In particular for `KafkaClient::fetch_group_topic_offsets` and `KafkaClient::fetch_group_offsets` a return value of `Map<String, Vec<PartitionOffset>>` as you implied would be desirable. This will definitely avoid the needless cloning and help clients in processing the response more easily. Feel free to go ahead.
* For `KafkaClient::produce_message`, which also returns `TopicPartitionOffsets`, the situation is a bit unclear. As you can see from the [TODO in the code](https://github.com/spicavigo/kafka-rust/blob/master/src/client/mod.rs#L1013) the return value should be changed anyway especially in regards to partitions which failed to acknowledge the data. Feel free to change it to a `Map<String, Vec<PartitionOffset>>` as well (me idea about the TODO is to return a `PartitionOffsetOrDataFailedToBeDelivered` in some future.)
* Regarding the `Result` within the structs. Well, the idea is to _not_ access the offsets value (i64) in the struct if kafka reported an error for the partition. This means the error can be only of type `kafka::error::KafkaCode`. I'm fine with changing it to `Result<i64, KafkaCode>` (i guess this will even reduce the size of the struct). The introduction of the `Result` in the two mentioned structs came after mistakenly ignoring the error in an earlier version of kafka-rust in the consumer. So I'm rather voting for keeping it.

**Comment by dead10ck** [comment]
> I agree that the existence of `TopicPartitionOffset` is sub-optimal. In particular for `KafkaClient::fetch_group_topic_offsets` and `KafkaClient::fetch_group_offsets` a return value of `Map<String, Vec<PartitionOffset>>` as you implied would be desirable. This will definitely avoid the needless cloning and help clients in processing the response more easily. Feel free to go ahead.

Cool, sounds good.

For the last two bullet points, yeah, it's not immediately clear how to handle the return value there. However, I think at least part of the confusion (at least for me) is that the Kafka broker's `ProduceResponse` contains *both* the offset and the error code, if any, so it doesn't really make sense to wrap the offset in a `Result` there anyway, since either way, the acknowledgement message will contain some offset.

For *fetching* group offsets, I think it makes sense to have them in a `Result` because either the offset exists, or returns -1, or some error happened. I think there are two ways to handle the errors when fetching offsets:

1. Wrap all partition/offset data into one top-level `Result`, with all offset data available if there were no errors. [This is currently what fetching does](https://github.com/spicavigo/kafka-rust/blob/master/src/client/mod.rs#L1365), so if the top-level `Result` returned by `__fetch_group_offsets` is `Ok`, then so will all the `offset` fields, so having to unwrap them is just unnecessary pain.
2. Handle partition errors individually (probably the more robust choice). In this case, knowing which partition failed to fetch its offsets is useful, so I think it does make sense to either store the partition data with its `Result` for the offset, which is what it's doing now, or just return a top-level `Result` that contains either the partition *and* offset together, or an `Err` that describes which partition it failed to fetch. (This way would also have the added benefit of being able to use `PartitionOffset` on the producer side as well.) Either way works, but in my opinion, while the latter is more of a pain to implement on the lib side, I think it makes error handling easier for the user-side. However, I defer to your judgment, since this is your lib :)

But right now, the current state of the lib is kind of inconsistent. It has a struct that contains a `Result` field as if to handle individual partition errors, but then doesn't really make use of it. I think if we're just going to quit on the first partition error, then having the `Result` field is just unnecessary. But handling partition errors individually may allow for more robust error handling, and allow the user to use the portion of the offsets that were fetched successfully. What do you think is the best way forward?

**Comment by dead10ck** [comment]
Also, just wanted to let you know that I don't often get free time to work on for-fun projects, so I can't promise I'll be able to move forward with this issue in a timely manner, unfortunately :/

**Comment by xitep** [comment]
> For the last two bullet points, yeah, it's not immediately clear how to handle the return value there. However, I think at least part of the confusion (at least for me) is that the Kafka broker's ProduceResponse contains both the offset and the error code, if any, so it doesn't really make sense to wrap the offset in a Result there anyway, since either way, the acknowledgement message will contain some offset.

i agree, it does make sense (especially if it's going to be `Result<i64, KafkaCode>`.) if i remember correctly, i didn't rework this due to the `protocol` structs being crate private and i didn't have to change the wire format parsing code. feel free to change this; but be sure to not skip reading any bytes from the parsed binary stream (i.e. always read the 2 byte error code _and_ always read the 4 byte offset, no matter what the error code says.) on the other hand, i'm fine with having the `protocol` module be "raw" and just a convenient thin layer above the binary raw wire format.

**Comment by xitep** [comment]
> For the last two bullet points, yeah, it's not immediately clear how to handle the return value there. However, I think at least part of the confusion (at least for me) is that the Kafka broker's ProduceResponse contains both the offset and the error code, if any, so it doesn't really make sense to wrap the offset in a Result there anyway, since either way, the acknowledgement message will contain some offset.

i agree, it does make sense (especially if it's going to be `Result<i64, KafkaCode>`.) if i remember correctly, i didn't rework this due to the `protocol` structs being crate private and i didn't have to change the wire format parsing code. feel free to change this; but be sure to not skip reading any bytes from the parsed binary stream (i.e. always read the 2 byte error code _and_ always read the 4 byte offset, no matter what the error code says.) on the other hand, i'm fine with having the `protocol` module be "raw" and just a convenient thin layer above the binary raw wire format.

regarding _fetching group offsets_ in `KafkaClient` i'm inclided to say that it's not entirely correct to fail the whole method call if there's an error for one partition partition - this seems like a bug to me! `KafkaClient::fetch_group_offsts` is supposed to be a mid-level abstraction layer. It has to provide enough details for clients such that they can make their decision (e.g. [here](https://github.com/spicavigo/kafka-rust/blob/master/examples/offset-monitor.rs#L131)) how to go about particular errors. on the other hand `KafkaClient` is supposed to deal transparently with certain error types, but not all of them. therefore i'd say it has to return either an "error or the offset" for a topic-partition in order to allow clients making up their own mind about how to deal with the facts. making the whole "fetch group offsets" method call fail due to an offset-error for only one partition, would push clients to make multiple calls to "fetch group offsets" for each partition separately. this is clearly inefficient as it result in a lot of overhead instead of one method call with all of the interested partitions specified.

regarding the inconsistency you are observing: this might be due to the fact that `kafka-rust` is layered:
* the `protocol` structs are - for the most part - not exposed to the public api and deal with encoding/decoding concerns - you can regard them as an implementation detail. 
* `KafkaClient` is a mid-level abstraction which tries to bring some more safety than the "protocol" layer; hence, the `Result` in certain structs exposed by `KafkaClient` or the dealing with "some" errors (i will have to investigate the error handling code you pointed out).
* `Producer` and `Consumer` on the other hand are supposed to be a high-level api; there should be not implementation details exposed. each layer has a different responsibility and therefore is different (or inconsistent with another layer.)

**Comment by dead10ck** [comment]
Ahh, ok, I understand. Ok, then for this ticket, I'll go ahead and plan to:

1. Change the fetch methods to return a map
2. Change the offset field in these two structs to a `Result<i64, KafkaCode>`

**Comment by xitep** [comment]
@dead10ck so, after inspecting the code you pointed out, reading the kafka protocol documentation again, and considering that `kafka-rust` does not provide any security related features ... after all this i fully agree with you that the current return value of the `fetch_group_(topic_)offsets` methods is non-sense. i would be glad if you could rework it just as you suggested. in particular i like the _"or just return a top-level Result that contains either the partition and offset together, or an Err that describes which partition it failed to fetch."_.

just to sum up my understanding of our discussion:

* the more general `fetch_group_offsets` would return a `Result<Map<String, Vec<PartitionOffset>, ErrorDescribingTopicsOrPartitionsDueToWhichTheWholeRequestFailed>` ?
* the topic related `fetch_group_topic_offsets` would return a `Result<Vec<PartitionsOffset>, ErrorDescr...>` ?
* `PartitionOffset` (in both of the above methods) would be a mere `struct PartitionOffset { partition: i32, offset: i64 }` (since the Ok(partitions-offsets) will not contain any errors) ?
* I'm of course fine with changing `protocol::PartitionProduceResponse` to contain the `Result<i64, KafkaCode>` (it's a private struct in the crate.)
* Given the changes to the `fetch_group_(topic_)offsets` methods, suddently `TopicPartitionOffset` becomes exposed to client code only through `produce_messages`. This gives a nice opportunity to replace it with a struct which is dedicated as a response for `produce_messages`; it can contain the mentioned `Result<i64, KafkaCode>` and would be later extended in future to return that data which failed to be delivered (for retry attempts.) `produce_messages` has already a dedicated struct for its input, namely `client::ProduceMessage` (the corresponding return struct replacing TopicPartitionOffset` could be named `ProduceConfirm` or similar; i'm not good at coming up with good names, feel free to make up one.) So `produce_messages` would return a `Result<Vec<ProduceConfirm>>` ?

can you confirm we are on the same line? many thanks so far!

**Comment by dead10ck** [comment]
Ah, ok, perfect! Yes, all of that sounds like what I was thinking of doing. Because my progress may be bursty, though, I think when I do make some progress, I'll open a work-in-progress PR, and I'll update it if I make any decisions outside of what you described while I work on it.

**Comment by xitep** [comment]
we've got this in master now. once again thanks for the hard work! it is really appreciated.

i'm going to keep this ticket open until the change gets pushed to creates.io. (i expect to do so next somewhere next week once i get back from vacation.)

**Comment by xitep** [comment]
just published on [crates.io](https://crates.io/crates/kafka/0.6.0); closing this ticket. many thanks! 👍
