### ISSUE TITLE
consumer: allow consuming multiple topics

### ISSUE THREAD

**Issue by Lingling7** [spicavigo/kafka-rust#31]
I'm trying to use a Rust consumer to read from multiple topics. This is the code I have now:
```rust
extern crate kafka;
use kafka::client::KafkaClient;
use kafka::consumer::Consumer;
use kafka::utils;
fn main(){
    let mut client = KafkaClient::new(vec!("localhost:9092".to_owned()));
    let res = client.load_metadata_all();
    let topics = client.topic_partitions.keys().cloned().collect(); 
    let offsets = client.fetch_offsets(topics, -1);
    for topic in &topics {
    let mut con = Consumer::new(client, "test-consumer-group".to_owned(), "topic".to_owned()).partition(0);
    let mut messagedata = 0;
    for msg in con {
        println!("{}", str::from_utf8(&msg.message).unwrap().to_string());
    }
  }
}

```
below is the error:

```
    src/main.rs:201:19: 201:25 error: use of moved value: `topics` [E0382]
src/main.rs:201     for topic in &topics {
                                  ^~~~~~
    note: in expansion of for loop expansion
    src/main.rs:201:5: 210:6 note: expansion site
    src/main.rs:167:40: 167:46 note: `topics` moved here because it has type `collections::vec::Vec<collections::string::String>`, which is non-copyable
    src/main.rs:167     let offsets = client.fetch_offsets(topics, -1);
                                                       ^~~~~~
    src/main.rs:203:37: 203:43 error: use of moved value: `client` [E0382]
    src/main.rs:203     let mut con = Consumer::new(client, "test-consumer-group".to_owned(), "topicname".to_owned()).partition(0);
                                                    ^~~~~~
    note: in expansion of for loop expansion
    src/main.rs:201:5: 210:6 note: expansion site
    note: `client` was previously moved here because it has type     `kafka::client::KafkaClient`, which is non-copyable
    error: aborting due to 2 previous errors
```
To better explain my question, here is my partial workable code for just one topic:
```rust
let mut con = Consumer::new(client, "test-consumer-group".to_owned(), "testtopic".to_owned()).partition(0);

for msg in con {
    println!("{}", str::from_utf8(&msg.message).unwrap().to_string());
}
```
And I tested the fetch_message function, it works for multiple topics, but the result I have (msgs) is Topicmessage, I don't know how to get message from Topicmessage.
```rust
let msgs = client.fetch_messages_multi(vec!(utils::TopicPartitionOffset{
                                            topic: "topic1".to_string(),
                                            partition: 0,
                                            offset: 0 //from the begining
                                            },
                                        utils::TopicPartitionOffset{
                                            topic: "topic2".to_string(),
                                            partition: 0,
                                            offset: 0
                                        },
                                        utils::TopicPartitionOffset{
                                            topic: "topic3".to_string(),
                                            partition: 0,
                                            offset: 0
                                        }));
for msg in msgs{
    println!("{}", msg);
}
```

**Comment by xitep** [comment]
hello @Lingling7,

the error message regarding `error: use of moved value: topics` is due to the fact that the call to `client.fetch_offsets(topics, -1)` "consumes" `topics` (a nice explanation and more details on this is the [ownership chapter of the rust book](https://doc.rust-lang.org/stable/book/ownership.html#move-semantics)). In particular, as part of #19 I would like to avoid the `client.fetch_offsets` and some other methods "consume" the topics in the long term. But for know you could work around this as follows:

```
    ...
    let topics: Vec<String> = client.topic_partitions.keys().cloned().collect(); 
    let offsets = client.fetch_offsets(topics.clone(), -1);
    ...
```

However, you'll still be left with the second error message. Unfortunately, `Consumer` does currently not provide the possibility to consume multiple topics (this might be possible in some future point in time; I'll leave this issue open for the moment in case we want to address this.)

As you noted you can use `client.fetch_messages_multi`, but you're left with managing the offsets yourself (here's an example of a small program consuming all messages of a given list of topics: https://github.com/xitep/monchan/blob/6239b9bc3c8bc49b9bac90379c3446c7364604e9/src/main.rs#L184).

Regarding your question about how to get to the "message" of a `TopicMessage`. You're already there :) Use "`{:?}`" instead of "`{}`" when printing the topic-message or access the members of [TopicMessages](https://github.com/spicavigo/kafka-rust/blob/master/src/utils.rs#L12) directly:

```
let msgs = client.fetch_messages_multi(...);
for msg in msgs {
    println!("msg.topic: {}", msg.topic);
    println!("msg.partition: {}", msg.partition);
    println!("msg.message: {}", msg.message); // this is the actual data of the message (you again need to "convert" it from raw bytes to something meaningful, e.g. `str::from_utf8(&msg.message).unwrap()`)
}
```

I hope this helps a little bit

**Comment by Lingling7** [comment]
@xitep  Thank you so much! I changed my code as you guided, still have the following error:
```
src/main.rs:192:37: 192:46 error: attempted access of field `topic` on type `collections::vec::Vec<kafka::utils::TopicMessage>`, but no field with that name was found
src/main.rs:192         println!("msg.topic: {:?}", msg.topic);
                                                    ^~~~~~~~~
note: in expansion of format_args!
<std macros>:2:25: 2:56 note: expansion site
<std macros>:1:1: 2:62 note: in expansion of print!
<std macros>:3:1: 3:54 note: expansion site
<std macros>:1:1: 3:58 note: in expansion of println!
src/main.rs:192:9: 192:48 note: expansion site
note: in expansion of for loop expansion
src/main.rs:190:5: 195:6 note: expansion site
src/main.rs:193:41: 193:54 error: attempted access of field `partition` on type `collections::vec::Vec<kafka::utils::TopicMessage>`, but no field with that name was found
src/main.rs:193         println!("msg.partition: {:?}", msg.partition);
                                                        ^~~~~~~~~~~~~
note: in expansion of format_args!
<std macros>:2:25: 2:56 note: expansion site
<std macros>:1:1: 2:62 note: in expansion of print!
<std macros>:3:1: 3:54 note: expansion site
<std macros>:1:1: 3:58 note: in expansion of println!
src/main.rs:193:9: 193:56 note: expansion site
note: in expansion of for loop expansion
src/main.rs:190:5: 195:6 note: expansion site
src/main.rs:194:39: 194:50 error: attempted access of field `message` on type `collections::vec::Vec<kafka::utils::TopicMessage>`, but no field with that name was found
src/main.rs:194         println!("msg.message: {:?}", msg.message);
                                                      ^~~~~~~~~~~
note: in expansion of format_args!
<std macros>:2:25: 2:56 note: expansion site
<std macros>:1:1: 2:62 note: in expansion of print!
<std macros>:3:1: 3:54 note: expansion site
<std macros>:1:1: 3:58 note: in expansion of println!
src/main.rs:194:9: 194:52 note: expansion site
note: in expansion of for loop expansion
src/main.rs:190:5: 195:6 note: expansion site
error: aborting due to 3 previous errors
```

**Comment by xitep** [comment]
@Lingling7 it's a bit hard for me to guess what's going on ... but i think this might be it: can you please try the following:

```
let msgs = client.fetch_messages_multi(...).unwrap(); // <-- unwrap() here
for msg in msgs {
   ....
}
````

previously i have (errornously) suggested the same without "unwrapping" and since `Result` (which is returned by `fetch_messages_multi` implements `IntoIterator` it works smoothly with the `for` loop; however, it leaves you with `msg` being of type `Vec<TopicMessage>` which, of course, doesn't have the attributes you are reaching for. i'm sorry for the confusion.

**Comment by Lingling7** [comment]
@xitep  Problem solved! Thanks for your help again!!!

**Comment by xitep** [comment]
:)

**Comment by Lingling7** [comment]
Hi, I'm trying to fetch topics by batch. For the fetch multiple topics messages, can I fetch one messages from one topic per time? such as:
```
topic 1, offset:1
topic 2, offset:1
topic 1, offset:2
topic 2, offset:2
......
```
Currently, the code fetching order is fetch all messages in one topic then go to the next topic.

**Comment by xitep** [comment]
Hello @Lingling7,

fetching messages one-by-one from topics/partitions is something kafka is not designed for. It'll hand out messages in "chunks" from topics/partitions (for efficiency reasons). Since these chunks might be a few hundred messages (for example) it might leave you in the impression that the client first consumes one topic and only then another. But what you really get is a mix of these chunks, which might well originate from different topics.

**Comment by xitep** [comment]
consuming multiple topics is prepared in the branch `consumer-mutli-topic`; want to try it out, @Lingling7? this would be the code to set up a consumer for two topics:

```rust
let mut consumer =
   Consumer::from_hosts(vec!("localhost:9092".to_owned()))
      .with_topic("my-topic-1".to_owned())
      .with_topic("my-topic-2".to_owned())
      .create()
      .unwrap();
loop {
  for ms in consumer.poll().unwrap().iter() {
    for m in ms.messages() {
      println!("{:?}", m);
    }
  }
}
```

This would currently be required in `Cargo.toml` in an example project:

```toml
[dependencies]
...
kafka = { git = "https://github.com/spicavigo/kafka-rust.git", branch = "consumer-mutli-topic" }
...
```

any feedback would be greatly appreciated.

**Comment by xitep** [comment]
Merged to `master`; re-opening until published on crates.io as 0.4.

**Comment by xitep** [comment]
Published on [crates.io](https://crates.io/crates/kafka/0.4.0).
