### ISSUE TITLE
Specify Kafka Protocol Version

### ISSUE THREAD

**Issue by godel9** [spicavigo/kafka-rust#36]
I've been playing around with this library, and it appears to not work with Kafka version 0.8.2.1 as I keep getting unexpected EOF errors. Does this library just not support Kafka 0.8 or am I doing something wrong?

**Comment by xitep** [comment]
`master` seems to be working fine for me (tried against latest https://hub.docker.com/r/spotify/kafka/ now). which version of kafka-rust are you using? in case you're using the version from crates.io, could you trie with this dependency definition?

```
[dependencies.kafka]
git = "https://github.com/spicavigo/kafka-rust.git"
```

**Comment by godel9** [comment]
I was using the crates.io version, switching to using the git repo fixed the problem. Thanks!
Unrelated question: what kind of performance can I expect for consuming from a single topic? Could this library handle reading several hundred thousand messages a second? Has anyone tried?

**Comment by xitep** [comment]
@godel9 i tried this scenario and was able to achieve a ~100k msg/s (a single client thread since kafka-rust is  not thread-safe yet) the performance of kafka-rust is currently not very good. there is still a lot of work necessary to get it perform really well. but i'm hopeful we can achieve this in future. after all, rust can be blazingly fast.

**Comment by xitep** [comment]
@spicavigo maybe it would be worth publishing the current master to crates.io?

**Comment by xitep** [comment]
just pushed the latest master to [crates.io](https://crates.io/crates/kafka). closing this one. @godel9 feel free to re-open in case there's more to be done.
